### ISSUE TITLE
sendinblue/api-v3-sdk is abandoned

### ISSUE THREAD

**Issue by rbouma** [dadolun95/magento2-brevo-sendinblue#3]
Just a reminder that the package sendinblue/api-v3-sdk is abandoned, you should avoid using it. Use getbrevo/brevo-php instead

**Comment by dadolun95** [comment]
Thanks for the remainder @rbouma i totally lost the release of the new brevo php sdk.
I've updated the repository to 1.0.14 version.
Now the module use getbrevo/brevo-php instead of  sendinblue/api-v3-sdk

PS: Since the repository is not very popular, if you like my work and it helps you star the repository. Thank you very much for your contribution.

**Comment by rbouma** [comment]
@dadolun95 Thanks for creating this module. Its way better than the original :)
